# models/tax_settings.py
"""
Atomic invoice-number sequence counters. Kept as its own tiny table (not the
usual platform_settings JSON blob) because invoice numbering needs a real
row-level lock on increment - two invoices generated in the same instant
must never get the same number, which a read-then-write on a JSON string
value cannot safely guarantee under concurrency.

Company GSTIN / legal name / registered address deliberately do NOT get a
dedicated table - they follow the existing platform_settings key/value
pattern (see app/utils/tax_engine.py's COMPANY_PROFILE_KEYS), matching how
commission.py and billing.py already store admin-tunable constants. There
is no real Drop Cars GSTIN/legal entity in this codebase yet (confirmed by
repo-wide search) - an Owner must fill these in via the settings endpoint
before any invoice generated by this module is legally valid to issue.
"""
from sqlalchemy import Column, String, Integer, TIMESTAMP, func
from app.database.session import Base


class InvoiceSequence(Base):
    """One row per (series, financial_year) - e.g. ("RIDE", "26-27"),
    ("DRVCOMM", "26-27"). `last_number` is incremented under a row lock
    (see app/crud/tax_invoices.py's next_invoice_number) so concurrent
    invoice creation can never collide or skip-and-reuse a number, which
    would break GST sequential-numbering compliance."""
    __tablename__ = "invoice_sequences"

    series = Column(String, primary_key=True)
    financial_year = Column(String, primary_key=True)
    last_number = Column(Integer, nullable=False, server_default='0')
    updated_at = Column(TIMESTAMP(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
