"""The one self-contained mobile page of the web execution portal (served by the API itself at /p/{token}, nothing else to host).
Plain JS, no libraries; every value from the server is put on the page with textContent, never as HTML (the QR codes are the only SVG we
inject, and they are generated by the server)."""

PAGE = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Drop Cars - Trip</title>
<style>
:root{--bg:#f4f6fb;--card:#fff;--ink:#14213d;--mute:#64748b;--line:#e2e8f0;--pri:#0ea5e9;--ok:#16a34a;--warn:#d97706;--bad:#dc2626}
@media(prefers-color-scheme:dark){:root{--bg:#0b1220;--card:#131c2e;--ink:#e8eefc;--mute:#94a3b8;--line:#243049}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
.wrap{max-width:520px;margin:0 auto;padding:14px}
h1{font-size:18px;margin:6px 0 2px}.sub{color:var(--mute);font-size:12.5px;margin-bottom:12px}
.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:14px;margin-bottom:12px}
.card h2{font-size:14px;margin:0 0 8px;text-transform:uppercase;letter-spacing:.04em;color:var(--mute)}
.row{display:flex;justify-content:space-between;gap:10px;padding:5px 0;border-bottom:1px dashed var(--line)}.row:last-child{border:0}
.row b{text-align:right}
label{display:block;font-size:12.5px;color:var(--mute);margin:10px 0 4px}
input,textarea{width:100%;padding:12px;border:1px solid var(--line);border-radius:10px;background:var(--bg);color:var(--ink);font-size:16px}
button{width:100%;padding:14px;border:0;border-radius:12px;background:var(--pri);color:#fff;font-weight:700;font-size:16px;margin-top:12px}
button.alt{background:transparent;color:var(--pri);border:1.5px solid var(--pri)}
button:disabled{opacity:.55}
.pill{display:inline-block;padding:3px 10px;border-radius:99px;font-size:12px;font-weight:700}
.ok{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#92400e}.bad{background:#fee2e2;color:#991b1b}
.msg{padding:10px 12px;border-radius:10px;margin:8px 0;font-size:14px}.msg.err{background:#fee2e2;color:#991b1b}.msg.good{background:#dcfce7;color:#166534}
.qr{text-align:center;margin:10px 0}.qr svg{max-width:100%;height:auto;background:#fff;padding:6px;border-radius:8px}
.stars{display:flex;gap:6px;justify-content:center;margin:10px 0}.stars span{font-size:38px;cursor:pointer;color:#cbd5e1}.stars span.on{color:#f59e0b}
a.btn{display:block;text-align:center;text-decoration:none;padding:13px;border-radius:12px;background:var(--ok);color:#fff;font-weight:700;margin-top:10px}
.small{font-size:12px;color:var(--mute)}
</style></head><body><div class="wrap" id="app"><div class="card">Loading...</div></div>
<script>
var MODE="__MODE__",TOKEN="__TOKEN__",API="/api/portal/"+TOKEN,state=null,busy=false,watch=null,lastPing=0,rating=0,msg=null;
function el(t,a,k){var e=document.createElement(t);if(a)for(var i in a){if(i==="class")e.className=a[i];else if(i==="text")e.textContent=a[i];else if(i.slice(0,2)==="on")e[i]=a[i];else e.setAttribute(i,a[i]);}
 (k||[]).forEach(function(c){if(c)e.appendChild(typeof c==="string"?document.createTextNode(c):c)});return e}
function money(n){return n==null?"-":"₹"+Number(n).toLocaleString("en-IN")}
function api(path,opt){return fetch(API+path,opt).then(function(r){return r.json().catch(function(){return{}}).then(function(j){if(!r.ok)throw new Error(j.detail||"Something went wrong");return j})})}
function post(path,obj){return api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(obj)})}
function load(){return api("").then(function(j){state=j;render()}).catch(function(e){document.getElementById("app").replaceChildren(el("div",{class:"card"},[el("h1",{text:"Drop Cars"}),el("div",{class:"msg err",text:e.message})]))})}
function run(fn){if(busy)return;busy=true;msg=null;fn().then(function(m){msg={ok:true,t:m||""};return load()}).catch(function(e){msg={ok:false,t:e.message};render()}).then(function(){busy=false})}
function kv(card,k,v){if(v!=null&&v!=="")card.appendChild(el("div",{class:"row"},[el("span",{text:k}),el("b",{text:String(v)})]))}
function banner(){return msg&&msg.t?el("div",{class:"msg "+(msg.ok?"good":"err"),text:msg.t}):null}
function trip(s){var c=el("div",{class:"card"},[el("h2",{text:"Booking #"+s.booking_id})]);
 kv(c,"Route",s.route);kv(c,"Pickup",s.pickup_at_ist);kv(c,"Vehicle",s.vehicle);kv(c,"Trip",s.trip_type);if(s.distance_km)kv(c,"Distance","~"+s.distance_km+" km");kv(c,"Trip earning",s.earning?money(s.earning):"");return c}
function feedbackPage(){var app=document.getElementById("app");app.replaceChildren();
 var c=el("div",{class:"card"},[el("h1",{text:"How was your trip?"}),el("div",{class:"sub",text:"Your feedback goes straight to Drop Cars."})]);
 var st=el("div",{class:"stars"});for(var i=1;i<=5;i++)(function(n){var s=el("span",{text:"★",onclick:function(){rating=n;[].forEach.call(st.children,function(x,k){x.className=k<n?"on":""})}});st.appendChild(s)})(i);
 var t=el("textarea",{rows:"3",placeholder:"Anything we should know? (optional)"});
 var b=el("button",{text:"Send rating",onclick:function(){if(!rating){msg={ok:false,t:"Tap the stars first"};return feedbackPage()}b.disabled=true;
   post("/feedback",{rating:rating,text:t.value}).then(function(){app.replaceChildren(el("div",{class:"card"},[el("h1",{text:"Thank you!"}),el("div",{class:"msg good",text:"Your rating was saved. Have a safe journey."})]))}).catch(function(e){msg={ok:false,t:e.message};b.disabled=false;feedbackPage()})}});
 c.appendChild(st);c.appendChild(t);var bn=banner();if(bn)c.appendChild(bn);c.appendChild(b);app.appendChild(c)}
function field(c,label,id,attrs){c.appendChild(el("label",{text:label}));var i=el("input",Object.assign({id:id},attrs||{}));c.appendChild(i);return i}
function val(id){return document.getElementById(id).value}
function photoUpload(path,fields){var fd=new FormData();for(var k in fields)fd.append(k,fields[k]);var f=document.getElementById("photo").files[0];if(f)fd.append("photo",f);return api(path,{method:"POST",body:fd})}
function share(){if(!navigator.geolocation||watch!==null)return;if(!state||(state.status!=="TAKEN"&&state.status!=="STARTED"))return;
 watch=navigator.geolocation.watchPosition(function(p){var n=Date.now();if(n-lastPing<20000)return;lastPing=n;post("/location",{lat:p.coords.latitude,lng:p.coords.longitude}).catch(function(){})},function(){},{enableHighAccuracy:true,maximumAge:10000})}
function render(){if(MODE==="feedback")return feedbackPage();var app=document.getElementById("app"),s=state;app.replaceChildren();
 app.appendChild(el("h1",{text:"Drop Cars"}));app.appendChild(el("div",{class:"sub",text:"One Way Drop Taxi - trip link"}));
 if(s.cancelled){app.appendChild(el("div",{class:"msg err",text:"This booking was cancelled. Please do not go for this trip."}));app.appendChild(trip(s));return}
 app.appendChild(trip(s));var b=banner();if(b)app.appendChild(b);
 if(s.status==="OPEN"){var c=el("div",{class:"card"},[el("h2",{text:"Take this booking"}),el("div",{class:"small",text:"The first person to send the details gets the booking. Give the driver who will actually drive."})]);
  field(c,"Driver full name","n",{autocomplete:"name"});field(c,"Driver mobile (10 digits)","p",{inputmode:"numeric",maxlength:"10"});field(c,"Vehicle number (TN 01 AB 1234)","v",{autocapitalize:"characters"});field(c,"Cab model (optional)","m");
  c.appendChild(el("button",{text:"Take this booking",onclick:function(){run(function(){return post("/take",{name:val("n"),phone:val("p"),vehicle_number:val("v"),vehicle_model:val("m")}).then(function(){return "Booking is yours. Pay the commission next."})})}}));app.appendChild(c);return}
 var e=s.executor;if(e){var d=el("div",{class:"card"},[el("h2",{text:"Driver & cab"})]);kv(d,"Driver",e.name);kv(d,"Mobile",e.phone);kv(d,"Vehicle",e.vehicle_number+(e.vehicle_model?" - "+e.vehicle_model:""));app.appendChild(d)}
 var paid=s.commission_status==="CONFIRMED";
 if(!paid){var p=el("div",{class:"card"},[el("h2",{text:"Commission to Drop Cars"}),el("div",{class:"row"},[el("span",{text:"Amount"}),el("b",{text:money(s.commission_due)})])]);
  var pay=s.pay||{};if(pay.upi_qr_svg){var q=el("div",{class:"qr"});q.innerHTML=pay.upi_qr_svg;p.appendChild(q)}
  if(pay.upi_uri)p.appendChild(el("a",{class:"btn",href:pay.upi_uri,text:"Pay with UPI app"}));
  if(pay.upi_id)p.appendChild(el("div",{class:"small",text:"UPI ID: "+pay.upi_id+(pay.payee?" ("+pay.payee+")":"")}));else p.appendChild(el("div",{class:"small",text:"Call Drop Cars for the payment details: +91 "+(pay.helpline||"7200217986")}));
  if(s.commission_status==="REPORTED"){p.appendChild(el("div",{class:"msg good",text:"UTR received. Waiting for Drop Cars to confirm - this page opens the trip by itself."}))}
  else{field(p,"UTR / transaction ID after paying","u");p.appendChild(el("button",{class:"alt",text:"I have paid",onclick:function(){run(function(){return post("/pay",{utr:val("u")}).then(function(){return "Thank you - Drop Cars will confirm the payment shortly."})})}}))}
  app.appendChild(p);share();return}
 var cu=el("div",{class:"card"},[el("h2",{text:"Customer"})]);
 if(s.customer){kv(cu,"Name",s.customer.name);kv(cu,"Mobile",s.customer.phone);cu.appendChild(el("a",{class:"btn",href:"tel:"+s.customer.phone,text:"Call customer"}))}
 else cu.appendChild(el("div",{class:"msg warn",text:s.customer_notice||"The customer's number opens soon."}));app.appendChild(cu);share();
 if(s.status==="TAKEN"){var t=el("div",{class:"card"},[el("h2",{text:"Start trip"}),el("div",{class:"small",text:"Ask the customer for the start OTP at pickup. Drop Cars staff cannot give it."})]);
  field(t,"Start OTP (from the customer)","so",{inputmode:"numeric",maxlength:"4"});field(t,"Odometer reading (km)","sk",{inputmode:"numeric"});t.appendChild(el("label",{text:"Odometer photo"}));t.appendChild(el("input",{id:"photo",type:"file",accept:"image/*",capture:"environment"}));
  t.appendChild(el("button",{text:"Start trip",onclick:function(){run(function(){return photoUpload("/start",{otp:val("so"),km:val("sk")}).then(function(){return "Trip started. Drive safe!"})})}}));app.appendChild(t)}
 if(s.status==="STARTED"){var x=el("div",{class:"card"},[el("h2",{text:"End trip"}),el("div",{class:"small",text:"Started at "+s.start_km+" km. Ask the customer for the end OTP at the drop."})]);
  field(x,"End OTP (from the customer)","eo",{inputmode:"numeric",maxlength:"4"});field(x,"Odometer reading (km)","ek",{inputmode:"numeric"});x.appendChild(el("label",{text:"Odometer photo"}));x.appendChild(el("input",{id:"photo",type:"file",accept:"image/*",capture:"environment"}));
  x.appendChild(el("button",{text:"End trip",onclick:function(){run(function(){return photoUpload("/end",{otp:val("eo"),km:val("ek")}).then(function(){return "Trip ended. Thank you!"})})}}));app.appendChild(x);
  if(s.feedback_qr_svg)qrCard(app,s)}
 if(s.status==="ENDED"){app.appendChild(el("div",{class:"msg good",text:"Trip finished: "+(s.end_km-s.start_km)+" km. Thank you for driving with Drop Cars."}));qrCard(app,s)}}
function qrCard(app,s){if(!s.feedback_qr_svg)return;var f=el("div",{class:"card"},[el("h2",{text:"Customer feedback"}),el("div",{class:"small",text:"Ask the customer to scan this QR and rate the trip."})]);var q=el("div",{class:"qr"});q.innerHTML=s.feedback_qr_svg;f.appendChild(q);app.appendChild(f)}
if(MODE==="feedback"){render()}else{load();setInterval(function(){if(!busy&&document.activeElement&&document.activeElement.tagName!=="INPUT"&&document.activeElement.tagName!=="TEXTAREA")load()},15000)}
</script></body></html>
"""


def render(mode: str, token: str) -> str:
    safe = "".join(ch for ch in (token or "") if ch.isalnum() or ch in "-_")
    return PAGE.replace("__MODE__", "feedback" if mode == "feedback" else "trip").replace("__TOKEN__", safe)
