<?php
/**
 * Admin App (React Native) view of customer reward-redemption claims
 * (generated by pages/customer-dashboard.php's "Redeem Now" flow). No
 * website admin page manages these at all today - a customer redeems
 * their referral_balance into a `referral_claims` row (status 'pending')
 * and a redeem_code, then "presents it to support to claim" - this is the
 * first staff-facing surface for that queue, on the website admin's own
 * MySQL `referral_claims` table.
 *
 * Auth: header `X-Admin-App-Key` must match ADMIN_APP_API_KEY
 * (config/env.php).
 *
 * GET  ?status=pending|claimed|all (default pending)
 *      -> { success, claims: [...] }
 * POST { action: 'mark_claimed', id }
 *      -> { success, message }
 */

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, X-Admin-App-Key');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

require_once __DIR__ . '/../config/env.php';
require_once __DIR__ . '/../admin/config/database.php'; // $pdo / $GLOBALS['db']
require_once __DIR__ . '/../admin/includes/enquiries-schema.php'; // dropcars_ensure_referral_tables

$pdo = $GLOBALS['db'] ?? null;
if (!$pdo) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Database unavailable']);
    exit;
}

$providedKey = $_SERVER['HTTP_X_ADMIN_APP_KEY'] ?? '';
if (!defined('ADMIN_APP_API_KEY') || ADMIN_APP_API_KEY === '' || !hash_equals((string) ADMIN_APP_API_KEY, (string) $providedKey)) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Invalid or missing admin app key']);
    exit;
}

if (function_exists('dropcars_ensure_referral_tables')) {
    dropcars_ensure_referral_tables($pdo);
}

if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    try {
        $status = trim((string) ($_GET['status'] ?? 'pending'));
        $where = '1=1';
        if (in_array($status, ['pending', 'claimed'], true)) {
            $where = 'rc.`status` = ' . $pdo->quote($status);
        }

        $stmt = $pdo->query("SELECT rc.*, c.`name` AS customer_name, c.`phone` AS customer_phone
            FROM `referral_claims` rc
            LEFT JOIN `customers` c ON c.`id` = rc.`customer_id`
            WHERE $where
            ORDER BY rc.`created_at` DESC
            LIMIT 200");
        $rows = $stmt ? $stmt->fetchAll(PDO::FETCH_ASSOC) : [];

        echo json_encode([
            'success' => true,
            'claims' => array_map(static function (array $r): array {
                return [
                    'id' => (int) $r['id'],
                    'customer_name' => $r['customer_name'] ?? 'Guest',
                    'customer_phone' => $r['customer_phone'] ?? '',
                    'amount' => (float) $r['amount'],
                    'redeem_code' => $r['redeem_code'],
                    'status' => $r['status'],
                    'created_at' => $r['created_at'],
                ];
            }, $rows),
        ]);
    } catch (Throwable $e) {
        http_response_code(500);
        echo json_encode(['success' => false, 'message' => 'Failed to load claims: ' . $e->getMessage()]);
    }
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $input = json_decode(file_get_contents('php://input'), true) ?: [];
    $action = trim((string) ($input['action'] ?? ''));

    try {
        if ($action === 'mark_claimed') {
            $id = (int) ($input['id'] ?? 0);
            if ($id <= 0) {
                http_response_code(400);
                echo json_encode(['success' => false, 'message' => 'Missing id']);
                exit;
            }
            $stmt = $pdo->prepare("SELECT `status` FROM `referral_claims` WHERE `id` = ?");
            $stmt->execute([$id]);
            $current = $stmt->fetchColumn();
            if ($current === false) {
                http_response_code(404);
                echo json_encode(['success' => false, 'message' => 'Claim not found']);
                exit;
            }
            if ($current === 'claimed') {
                http_response_code(400);
                echo json_encode(['success' => false, 'message' => 'This claim was already marked as claimed']);
                exit;
            }
            $pdo->prepare("UPDATE `referral_claims` SET `status` = 'claimed' WHERE `id` = ?")->execute([$id]);
            echo json_encode(['success' => true]);
        } else {
            http_response_code(400);
            echo json_encode(['success' => false, 'message' => 'Unknown action']);
        }
    } catch (Throwable $e) {
        http_response_code(500);
        echo json_encode(['success' => false, 'message' => 'Action failed: ' . $e->getMessage()]);
    }
    exit;
}

http_response_code(405);
echo json_encode(['success' => false, 'message' => 'Method not allowed']);
